### ISSUE TITLE
Creating an tale instance 

### ISSUE THREAD

**Issue by ian-taylor** [whole-tale/girder_wholetale#10]
Creating a tale using a valid tale ID from the Girder API: https://girder.wholetale.org/api/v1#!/tale/tale_createTale gives the following error:
 
{
  "message": "SSLError: SSLError(SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)'),),)",
  "trace": [
    [
      "/girder/girder/api/rest.py",
      561,
      "endpointDecorator",
      "val = fun(self, args, kwargs)"
    ],
    [
      "/girder/girder/api/rest.py",
      1125,
      "POST",
      "return self.handleRoute(method, path, params)"
    ],
    [
      "/girder/girder/api/rest.py",
      884,
      "handleRoute",
      "val = handler(**kwargs)"
    ],
    [
      "/girder/girder/api/access.py",
      68,
      "wrapped",
      "return args[0](*iargs, **ikwargs)"
    ],
    [
      "/girder/girder/api/describe.py",
      575,
      "wrapped",
      "return fun(*args, **kwargs)"
    ],
    [
      "/girder/plugins/wholetale/server/rest/instance.py",
      137,
      "createInstance",
      "save=True)"
    ],
    [
      "/girder/plugins/wholetale/server/models/instance.py",
      93,
      "createInstance",
      "resp = requests.post(hub_url, json=payload)"
    ],
    [
      "/usr/local/lib/python2.7/dist-packages/requests/api.py",
      110,
      "post",
      "return request('post', url, data=data, json=json, **kwargs)"
    ],
    [
      "/usr/local/lib/python2.7/dist-packages/requests/api.py",
      56,
      "request",
      "return session.request(method=method, url=url, **kwargs)"
    ],
    [
      "/usr/local/lib/python2.7/dist-packages/requests/sessions.py",
      488,
      "request",
      "resp = self.send(prep, **send_kwargs)"
    ],
    [
      "/usr/local/lib/python2.7/dist-packages/requests/sessions.py",
      609,
      "send",
      "r = adapter.send(request, **kwargs)"
    ],
    [
      "/usr/local/lib/python2.7/dist-packages/requests/adapters.py",
      497,
      "send",
      "raise SSLError(e, request=request)"
    ]
  ],
  "type": "internal”
}

**Comment by Xarthisius** [comment]
SSL expired, it should be fixed now.

**Comment by ian-taylor** [comment]
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' --header 'Girder-Token: Mb4s9ziBtnywEtlbmKshCkVOTaVZEiQbnTBulWJdShtIGRRJJyrUvtDOXnlwnzPa' 'https://girder.wholetale.org/api/v1/instance?taleId=58ca9770b270e80001b45c82&name=Mine'

Still gives an error:

{
  "message": "Got 500 code from tmpnb, response=\"<html><title>500: Internal Server Error</title><body>500: Internal Server Error</body></html>\"/",
  "type": "rest"
}

from the girder API:

https://girder.wholetale.org/api/v1#!/instance/instance_createInstance
