### ISSUE TITLE
Investigate DataONE File Registration Issues

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#141]
I've been having a hard time registering data from DataONE-most of the packages that I've been trying to register aren't found.

I have noticed that packages from the ADC have a higher success rate. 
I don't recall having this many failures in the past-so investigate why there are failures and fix them.

**Comment by amoeba** [comment]
Makes sense to test https://github.com/whole-tale/girder_wholetale/blob/05981a42c28915bf9c5d943e6f0df7eed4ce0f69/server/dataone_register.py#L173-L181 first. arcticdata.io didn't change its URL structure so that makes sense it'd still work

**Comment by amoeba** [comment]
Yeah, if you take a URL from search.dataone.org and add the # back in it works. Interestingly, without it, you get garbage back from the API.

For example, https://search.dataone.org/view/https://pasta.lternet.edu/package/metadata/eml/knb-lter-luq/127/1676153 returns `1676153`.

**Comment by ThomasThelen** [comment]
The change regarding `#view` and `/view` have been deployed on production for the AHM

**Comment by Xarthisius** [comment]
https://github.com/whole-tale/girder_wholetale/commit/85749f2aff300e908e04f5e009a594b1901aa1f3
