### ISSUE TITLE
Create an Endpoint that Generates SHA1/md5 for Files

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#155]
For efficiency reasons, we should be hashing the files from girder_wholetale rather than from gwvolman. To do this, create an endpoint that takes a list of item Ids, hashes the associated files, and returns a structure with the ID: hash.

A similar example can be found [here](https://github.com/whole-tale/girder_wholetale/blob/master/server/__init__.py#L102-L134)

**Comment by Xarthisius** [comment]
Files exported via `GET /tale/{id}/export` annotated with md5 and sha256 checksums (#271). Do we need this anywhere else?

**Comment by ThomasThelen** [comment]
No we can close this
