### ISSUE TITLE
Add `doi` Field to the Tale Object

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#167]
After a Tale is published, we should persist the doi that was assigned to it. I propose that we do this in the Tale object.

To add this, we should
   1. Add & expose it to the tale fields during creation
   2. Bump the Tale format
   3. Refactor the unit tests

Any thoughts @Xarthisius?

**Comment by Xarthisius** [comment]
SGTM! We could use that during Tale importing to avoid double entries.

**Comment by Xarthisius** [comment]
Fixed by #203
