### ISSUE TITLE
Add import endpoint to support launching Tales using external identifiers

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#171]
For both DataONE and Dataverse integration, the user should be able to easily launch a Tale directly from the external website/repository.

Tentatively:
* POST /tale/import
* Required: 
  * external external identifier (URI)
  * imageId (environment)
* Optional
  * Tale name
  * Launch instance or not (default true)

The import endpoint will automatically register the associated file/dataset, create a Tale on behalf of the  user given the image and optional name, and optionally launch an instance of the tale.

Update design documentation https://docs.google.com/document/d/1R-WVkbYypLGrUdnkM6gl4Ex0YJa376B9D5eLH_2USlQ/edit

**Comment by Xarthisius** [comment]
Fixed by https://github.com/whole-tale/girder_wholetale/pull/173
