### ISSUE TITLE
Error while moving file(s)/folder(s) from home directory to a tale's workspace folder

### ISSUE THREAD

**Issue by cyberdante** [whole-tale/girder_wholetale#208]
Item with id `5c180831b2281900011b989b` (a file in this case) exists but when I try to move it using the `/resource/move` endpoint to move it from the `home` directory into the current tale's `workspace` folder, the operation fails and the user gets an error saying that the file does not exist. The same happens with a folder.

<img width="1902" alt="screen shot 2019-01-03 at 12 43 40 pm" src="https://user-images.githubusercontent.com/20361247/50693664-9ad45b80-1005-11e9-9fef-318b2ef703fd.png">

<img width="1081" alt="screen shot 2019-01-03 at 1 02 47 pm" src="https://user-images.githubusercontent.com/20361247/50693680-a4f65a00-1005-11e9-9bb0-8d2765fc821e.png">

**Comment by cyberdante** [comment]
Fwiw, I was able to move a file from one tale's workspace into another workspace from a different tale.

**Comment by Xarthisius** [comment]
No longer applicable + it should work now.
