### ISSUE TITLE
createTale has invalid default value for the description field

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/girder_wholetale#215]
### Steps to Reproduce
Once the PUT `/tale/:id` endpoint is integrated with the new `dataSet` changes from @Xarthisius' and my branches:
1. Compose a new Tale from the UI
2. Navigate to the `/run/:id` view
3. Click the Files tab and choose "External Data" if it is not already selected
4. Click the (+) button at the top-right of the file list
    * The Select Data Modal should appear
5. Open your browser's DevTools
6. Click "Select" at the bottom-right of the modal
    * The modal should dismiss
7. Check the Console and/or Network tabs in your browser's DevTools
    * You will see that the PUT has failed, and has given the following error:`{"message": "Invalid JSON object for parameter tale: None is not of type 'string'", "type": "rest"}`
    * NOTE: This is the bug
8. Click the "Metadata" tab
9. Add a description to this tale and click "Save" at the bottom
10. Repeat step 4-7 and check the console again
    * This time, the PUT that failed previously should succeed
    * NOTE: This is the fix

### Proposed Fix
The signature of the `createTale` method specifies a default value of `None` for `description`:
```python
    def createTale(self, image, data, creator=None, save=True, title=None,
                   description='', public=None, config=None, published=False,
                   authors=None, icon=None, category=None, illustration=None,
                   narrative=None):
         ...    ...    ...    ...    ...    ...    ...    ...    

        tale = {
            'authors': authors,
            'category': category,
            'config': config,
            'creatorId': creatorId,
            'dataSet': data or [],
            'description': description,
            'format': _currentTaleFormat,
            'created': now,
            'icon': icon,
            'iframe': image.get('iframe', False),
            'imageId': ObjectId(image['_id']),
            'illustration': illustration,
            'narrative': narrative or [],
            'title': title,
            'public': public,
            'published': published,
            'updated': now
        }
```

However, the schema specifies that this field must contain a string:
```js
        "description": {
            "type": "string",
            "description": "The description of the Tale (Markdown)"
        },
```

I am able to "Compose" a Tale from the UI, but I am not prompted for a description and the default value is used. Because `None` / `null` is not a string, attempting to PUT this same value back to `/tale/:id` throws a validation error.

I think that we should be able to change the default value of any required fields from `None` to instead use the empty string. This way, `''` is a valid string, whether the user explicitly sets it or not.

**Comment by ThomasThelen** [comment]
I actually ran across this some time ago and put the fix in the `dataone_publishing` branch [here](https://github.com/whole-tale/girder_wholetale/blob/dataone_publishing/server/schema/tale.py#L25). I may have written some unit tests for it too; I'll go ahead and make these changes to `master` if that's fine with you.

**Comment by bodom0015** [comment]
Oh, that's fantastic - I didn't even realize that the schema could take an array of values! That would be fine with me, unless @Xarthisius has objections?

From what I understand, the UI already populates the "Edit Tale" form with a default value of `#### Markdown Editor` if the description is null when the form finishes loading.

**Comment by Xarthisius** [comment]
Adding `null` to accepted values in schema SGTM!

**Comment by Xarthisius** [comment]
> * Change the schema to accept our default value (which is currently `None` / `null`)

I looked at Tommy's changes and I thought that ^^ is what you're ultimately suggesting. That'd be my preferred choice if I were to implement this. However, I'm fine with option 1 if you think that's a better way to go.

**Comment by bodom0015** [comment]
Ah, sorry for the mix-up... I don't have a strong opinion about it, but I had misinterpreted "SGTM" as "silently giggling to myself" and thought you were raising an objection :joy:
