### ISSUE TITLE
Update user data listing to use "my external data" filter

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#231]
Per investigation from  https://github.com/whole-tale/dashboard/issues/357#issuecomment-457343718, we COULD update the Girder `GET /folder` endpoint to support filtering by datasets on "my external data" (per https://github.com/whole-tale/girder_wholetale/pull/205).

With this change along with https://github.com/whole-tale/girder_wholetale/pull/205, the Manage > Data page will display my registered datasets using the new backend model with no UI changes.

We will only do this if https://github.com/whole-tale/dashboard/issues/357 proves to cumbersome.

**Comment by Xarthisius** [comment]
Obsolete
