### ISSUE TITLE
Tale Author schema causes internal conflicts in Job operations

### ISSUE THREAD

**Issue by bodom0015** [whole-tale/girder_wholetale#297]
From https://github.com/whole-tale/dashboard/pull/451#issuecomment-480403493,

#273 changed the format of the Tale authors from a simple string to an array of objects. There appear to be cases where this behavior is problematic.

### Steps to Reproduce
Submit a Job that requires the Girder worker to modify the Tale - if the Tale is invalid (and therefore unsavable) before the Job begins, then the Job will be unable to complete successfully. 

#### Scenario A
When creating a new Tale the user's orcid is not known, so we set the orcid to an empty string - this is invalid according to the schema and causes errors when attempting to submit the Tale for Publishing or Export the Tale.

1. Login to WholeTale Dashboard
2. Compose a Tale, and launch it
3. Navigate to the Run view
4. Attempt to Publish the Tale

#### Scenario B
When importing a Tale, the `orcid` field could not be known at the time of creation, and is left blank - this causes failures when attempting to register external data on the Tale during the "Analyze in WT" use case

1. Login to WholeTale Dashboard
2. Navigate to `/compose?name=Replication+Data+for%3A+The+Economic+Consequences+of+Partisanship+in+a+Polarized+Era&uri=https%3A%2F%2Fdataverse.harvard.edu%2Fapi%2Faccess%2Fdatafile%2F3020117`
3. Choose an environment and click Compose

### Expected Results
In both cases, the Job should successfully finish

### Actual Results
In both cases,  a cryptic error message is returned from `/api/v1/job/{id}/result`: `__init__() missing 3 required positional arguments: 'text', 'url', and 'method'`

**Comment by ThomasThelen** [comment]
@craig-willis @Xarthisius and I discussed how we throw an exception when we don't have an ORCID and we're going to require users to link their ORCID when they create a Whole Tale account. I don't think that this should be a problem once that's done and we set the ORCID field to an actual account.

**Comment by Xarthisius** [comment]
I believe this is now fixed. (with https://github.com/whole-tale/gwvolman/pull/65 and #298)
