### ISSUE TITLE
Refactor data registration to use LocalJob

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/girder_wholetale#306]
1. Wrap registration into a Job
2. Don't emit `progress` events, use `wt_progress` instead

**Comment by ThomasThelen** [comment]
Linking to [152](https://github.com/whole-tale/girder_wholetale/issues/152). I wonder if it makes sense to do this with exporting too (maybe we'll discuss on the dev call)

**Comment by Xarthisius** [comment]
> Linking to [152](https://github.com/whole-tale/girder_wholetale/issues/152). I wonder if it makes sense to do this with exporting too (maybe we'll discuss on the dev call)

Export is streaming data directly to the user. I don't think that's possible with a job.
