### ISSUE TITLE
Change GET /repository to include friendly name

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#374]
For discussion.

Per https://github.com/whole-tale/dashboard/pull/576#pullrequestreview-326208410 and https://github.com/whole-tale/dashboard/pull/576#issuecomment-561255869, the `/repository` endpoint now returns a list of targets (some with protocol, some without). This means the publish dropdown contains hostnames/URLs but not friendly names. What would it take to include a friendly name to display in the dropdown?

It looks to me like could simply update the `PUBLISHER_REPOS` dictionary to add a name field and change the endpoint accordingly:

https://github.com/whole-tale/girder_wholetale/blob/master/server/constants.py#L91-L97

For example:
```
PluginSettings.PUBLISHER_REPOS: [
  {
    "repository": "sandbox.zenodo.org", 
    "auth_provider": "zenodo",
    "name": "Zenodo Sandbox"
   },
  {
    "repository": "https://dev.nceas.ucsb.edu/knb/d1/mn",
    "auth_provider": "dataonestage2",
    "name": "DataONE Dev"
  },
]
```

**Comment by Xarthisius** [comment]
AFAIR Ember, and potentially Angular, doesn't like `name` attribute so please come up with a something different. Otherwise :+1:

**Comment by bodom0015** [comment]
Ember seemed to have issues with a field named `id`, but I think `name` was what we settled on for this particular pattern/issue: https://github.com/whole-tale/girder_wholetale/pull/364#issuecomment-546392404

Was there another similar instance that you were thinking of that I may have forgotten?

**Comment by Xarthisius** [comment]
> Ember seemed to have issues with a field named `id`, but I think `name` was what we settled on for this particular pattern/issue: [#364 (comment)](https://github.com/whole-tale/girder_wholetale/pull/364#issuecomment-546392404)
> 
> Was there another similar instance that you were thinking of that I may have forgotten?

No, I just remembered it wrongly. I'm old...
