### ISSUE TITLE
Importing Data as Read Only Fails, But Write Works

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#387]
https://dashboard.local.wholetale.org/browse?api=https%3A%2F%2Fcn.dataone.org%2Fcn%2Fv2&name=Sockeye%20salmon%20age%20measurements%20from%20scale%20data%2C%20Alaska%2C%202011-2017&uri=doi%3A10.5063%2FF1ZW1J77

To reproduce:
1. Visit the link above
2. Create a Read only Tale
3. See the error pasted below
4. Visit the link again
5. Select Read/Write
6. Create the Tale
7. Note that it works

Note that the path in is `Sockeye salmon age measurements from scale data Alaska 2011-2017`. The error shows that it's looking for a path with commas included. Note that this seems to work fine on stage?

```
HttpError: HTTP error 400: GET http://girder:8080/api/v1//resource/lookup?path=%2Fcollection%2FWholeTale+Catalog%2FWholeTale+Catalog%2FSockeye+salmon+age+measurements+from+scale+data%2C+Alaska%2C+2011-2017
Response text: {"message": "Path not found: collection/WholeTale Catalog/WholeTale Catalog/Sockeye salmon age measurements from scale data, Alaska, 2011-2017", "type": "validation"}
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/girder_worker/task.py", line 148, in __call__
    results = super(Task, self).__call__(*_t_args, **_t_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/gwvolman/gwvolman/tasks.py", line 606, in import_tale
    '/resource/lookup', parameters={'path': path})
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 503, in get
    return self.sendRestRequest('GET', path, parameters, jsonResp=jsonResp)
  File "/usr/local/lib/python3.5/dist-packages/girder_client/__init__.py", line 497, in sendRestRequest
    response=result)
```

**Comment by craig-willis** [comment]
I'm seeing this same problem locally, but not on stage -- apparently due to new filename sanitization process?

Dataset is registered as "Sockeye salmon age measurements from scale data Alaska 2011-2017" but lookup is looking for "Sockeye salmon age measurements from scale data, Alaska, 2011-2017"

On staging, both flavors are registered so the error is hidden.

**Comment by Xarthisius** [comment]
We do search by path in gwvolman task, which never was great idea...

**Comment by ThomasThelen** [comment]
This was fixed by Kacper's file path sanitation PR. Tested on RC2
