### ISSUE TITLE
Tale export doesn't include r2d version

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#388]
The tale imageInfo contains the repo2docker version used to build the image, but this information doesn't make it into the exported tale.

**Comment by ThomasThelen** [comment]
I'm leaning towards this going in the manifest. We can declare properties about repo2docker with a small [SoftwareApplication](https://schema.org/SoftwareApplication) blurb. I _think_ hasPart is appropriately used here.

```
{
    "schema:hasPart: [{
        "@id": "https://repo2docker.readthedocs.io",
        "@type": "schema:SoftwareApplication",
        "schema:softwareVersion": "version_number"
    }]
}
```

**Comment by ThomasThelen** [comment]
Should be 95% complete (I might have to bump the schema version) in [this branch](https://github.com/whole-tale/girder_wholetale/tree/add_repo2docker_version) but I'm prioritizing other work above this.
