### ISSUE TITLE
Add Support for Datasets With Multiple Resource Maps

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#39]
Currently, in `dataone_register.py` we raise an exception when a data object has multiple resource maps. Implement a way to narrow down the data maps to a single one.

Test case:
* Use `https://search.dataone.org/#view/https://doi.org/10.5061/dryad.kq484/2?ver=2018-01-08T13:41:30.404-05:00` as the target url.
* Run `dataone_register.py` with the url
+ See exception thrown

Alternatively,
* Use the url as the Reference URI in the modal "Search for Data Sources" dialog
+ See that there is one result, but a blank item in the dropdown
+ See that there is a missing folder name
* Click "Register"
+ See `Error: Item name must not be empty.`

**Comment by mbjones** [comment]
@ThomasThelen Because most duplication is due to the same object being in multiple versions of the same package, a reasonable algorithm could 1) check if the item is in multiple packages, and if it is, then forward chain to the most recent package version that contains that data item.
