### ISSUE TITLE
Dataverse is retiring installations-json

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#415]
According to @pdurbin, the "miniverse" URL used to identify Dataverse installations will be retired (https://services.dataverse.harvard.edu/miniverse/map/installations-json)

I know we cache this information, but maybe we should just add our own copy to the plugin until there's another way?

https://github.com/whole-tale/girder_wholetale/blob/master/server/constants.py#L35-L37

**Comment by craig-willis** [comment]
@pdurbin do you see any issue with us using the same method/file as you are in https://github.com/IQSS/dataverse-metrics/issues/48?  I'd rather rely on your cached and possibly updated list than something we cache and don't reliably maintain.

**Comment by pdurbin** [comment]
@craig-willis no, I don't see any issue with using that file. Heads up that I switched from URLs to just the hostname. Here's a direct link to the file: https://iqss.github.io/dataverse-installations/data/data.json

**Comment by craig-willis** [comment]
Thanks @pdurbin.
