### ISSUE TITLE
Relax DataONE URL regexes

### ISSUE THREAD

**Issue by amoeba** [whole-tale/girder_wholetale#46]
We're currently investigating removing the use of `#xzy` (fragments ids) in MetacatUI and @ThomasThelen noted that I hard-coded that in a couple of places:

https://github.com/whole-tale/girder_wholetale/blob/master/server/dataone_register.py#L110

Just relax the regex so it handles both the case with and without the #.

**Comment by ThomasThelen** [comment]
We made this change before the workshop at the last AHM and it has been deployed on dev.
