### ISSUE TITLE
Implement publishing job on the backend side

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#51]
Extend Girder API to call DataONE API to upload packaged tale. Depends on serialization format.

Completion criteria:
* Implement API
* Define tests
* Update API documentation
* PR
* Deploy to dev

**Comment by amoeba** [comment]
We didn't target this for MVP during the AHM. If everyone agrees, I think we should move this out of the MVP project and onto the next milestone.

**Comment by craig-willis** [comment]
Implemented in v0.7.
