### ISSUE TITLE
Tale's config is not preserved in environment.json during export/version creation.

### ISSUE THREAD

**Issue by Xarthisius** [whole-tale/girder_wholetale#514]
### How to reproduce?

1. Create a Tale with custom `config`, e.g. `{"foo": "bar"}`
2. Either export a bag or create a version.
3. Inspect `environment.json` (either in the bag, or in version folder)

### Expected result
`taleConfig` is present and equal to `{"foo": "bar"}`

### Actual result
No `taleConfig`.

### Notes
Originally reported by @matthew-a-dunlap via email.

**Comment by matthew-a-dunlap** [comment]
Thanks for fixing this for export/versioning. This seems to still be broken when using the `PUT` `/tale/{id}/restore` command. I've tested this via the girder page taking a tale with a version and restoring it.

Let me know if I can do anything else to help!

**Comment by Xarthisius** [comment]
@matthew-a-dunlap The fact it was merged doesn't necessarily mean it was deployed on .stage.

**Comment by matthew-a-dunlap** [comment]
@Xarthisius Works now! Thanks for pushing the feature.
