### ISSUE TITLE
Importing Tale from a published source

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#52]
Implementation of reading Tale packaging serialization in Girder API.

Completion criteria:
* Update Girder API
* Update documentation
* Define tests/unit tests
* PR
* Deploy to dev

**Comment by ThomasThelen** [comment]
Assigning this to myself to make sure this is working; will test after the virtual_resource merge

**Comment by Xarthisius** [comment]
I believe it has been done ages ago. We import Tales from e.g. Zenodo and Dataverse.
