### ISSUE TITLE
Investigate Nested Package Registration

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#56]
I'm noticing some issues when registering data packages from DataONE that are nested. Sometimes, the data packages don't show up in any of the file folders in the dashboard, for example, 
`https://search.dataone.org/#view/urn:uuid:6f5533ab-6508-4ac7-82a3-1df88ed4580e`

Other times I've noticed that packages get prematurely cut off and don't contain all of the original files that were in the packages.

**Comment by amoeba** [comment]
Interesting. What do you get if you run this through register_dataone_.py directly without Girder involved?

**Comment by ThomasThelen** [comment]
I dug a little deeper and was able to locate the file with the `/dataset` endpoint. It looks like this must be an issue with the dashboard not displaying the folder and not girder, so I'm going to move this issue over there.
