### ISSUE TITLE
run-local.sh is incorrect if image has never been built

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/girder_wholetale#566]
With https://github.com/whole-tale/girder_wholetale/pull/558 the image is always in the manifest so the check when generating `run-local.sh` is no longer valid (https://github.com/whole-tale/girder_wholetale/blob/master/server/lib/exporters/bag.py#L218). We need to check if the image actually exists in the registry.

**Steps to reproduce**
* Create a new tale, but don't build it
* Export it
* Inspect `run-local.sh`

**Expected results**
run-local.sh should contain command to build the image locally.

**Actual results**
It doesn't.

**Comment by Xarthisius** [comment]
Or we could always output `build_cmd` saying that you can use it if `docker run` returns image not found.
