### ISSUE TITLE
Handle Creating Packages With Over 1,000 Items

### ISSUE THREAD

**Issue by ThomasThelen** [whole-tale/girder_wholetale#84]
DataONE packages have a recommended limit of 1,000 objects because the landing page will lag when it's created by the server. Some tales might produce this many files and it wold be a good idea to add support for these.

I propose that when we approach the limit, we create a sibling package.

**Comment by ThomasThelen** [comment]
On second thought, it's probably a better idea to let DataONE tackle the performance issues centered around data packages with a high file count and leave Whole Tale out of it. It isn't practical/scalable to track the issues of connected repositories and program around their nuances that may be fixed in the future.

**Comment by Xarthisius** [comment]
> On second thought, it's probably a better idea to let DataONE tackle the performance issues centered around data packages with a high file count and leave Whole Tale out of it.

Agreed :)
